---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: attendee-service
- name: current-app-info

outputs:
- name: app-manifest-output

run:
  path: concourse-pipeline-samples/blue-green-app-deployment/ci/tasks/app-manifest-prep
