---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: "8"

inputs:
- name: attendee-service
- name: current-app-info

outputs:
- name: test-output

run:
  path: attendee-service/ci/tasks/smoke-test.sh

