---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: attendee-service
- name: current-app-info

run:
  path: attendee-service/ci/tasks/update-routes.sh
