---
resources:
- name: attendee-service
  type: git
  source:
    uri: https://github.com/deandemo/pcf-attendee-service-code   #<----- REPLACE ME
    branch: concourse_deployment

- name: deploy-attendee-service
  type: cf
  source:
    api: api.system.cumuluslabs.io
    username: {{cf-user}}
    password: {{cf-password}}
    organization: bdean-pal    #<----- REPLACE ME
    space: sandbox         #<----- REPLACE ME
    skip_cert_check: true

jobs:
- name: build
  public: true
  plan:
  - get: attendee-service
  - task: package
    file: attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

