---
resources:
- name: attendee-service
  type: git
  source:
    uri: https://github.com/deandemo/pcf-attendee-service-code   #<----- REPLACE ME
    branch: concourse_deployment

- name: deploy-attendee-service-blue
  type: cf
  source:
    api: {{cf-api}}
    username: {{cf-user}}
    password: {{cf-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}         #<----- REPLACE ME
    skip_cert_check: true

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - get: attendee-service
    trigger: true
  - task: unit-test
    file: attendee-service/ci/tasks/test/yml

- name: build
  serial: true
  public: true
  plan:
  - get: attendee-service
    trigger: true
    passed:
      - unit-tests
  - task: package
    file: attendee-service/ci/tasks/package.yml
  - put: deploy-attendee-service-blue
    params:
      manifest: attendee-service/manifest.yml
      path: package-output/attendee-service.jar

- name: verify-blue
  serial: true
  public: true
  plan:
  - get: attendee-service
    trigger: true
    passed:
      - build
  - task: smoke-blue
    file: attendee-service/ci/tasks/smoke-blue.yml
